### PR TITLE
Navbar updates: UI and system status

### PR DESCRIPTION
**Pull request by MrEminent42**
Revamped the UI to be along the lines of what's in the Figma. We talked about removing the center page buttons so I removed that. We also talked about saving the Login functionality for "if we have time" so instead, I added a system to display the currently selected property.

### CODE REVIEW

**Review by bri-personal — APPROVED** [review]
Great!

**Comment by bri-personal** [comment]
> Looks great. Just one thing- if I select a property and use the built in back button on my browser, the "Change property" link is still visible in the top right. Small bug, might not be worth fixing. Lmk what you think

I think we should fix it - The nav bar on the home page shouldn't show a specific address

**Comment by MrEminent42** [comment]
Noted. Since this requires a navigation overhaul I recommend we merge this for now and I'll fix #22 as part of the navigation overhaul. Thoughts?

**Review by geoffblay — APPROVED** [review]
LGTM, change property issue to be fixed later

**Pull request merged**
