### PR TITLE
Updating types with CLI

### PR DESCRIPTION
**Pull request by geoffblay**
General description of changes:
* Functionality for updating types locally via the command line with `npm run update-types`
* Moved definition for the database from supabaseClient.ts to the controller itself for automation purposes
* renamed supabaseClient.ts to supabase.ts for automation purposes
* added a GitHub workflow to automate updating types I think?

Breaking changes: 
* moving db definition to controller/changing file names, shouldn't be an issue but something to keep an eye on

Did you run `npm run before-pr`?
- [X] yes
- [ ] no

Does this PR fix/implement an Issue?
- [ ] yes, fixes #XX
- [X] no

Other notes:
HMU if you have issues running the script, might need to install/login to supabase CLI before running.

### CODE REVIEW

**Review by zachstoney30 — APPROVED** [review]
Needed a login + token for supabase but it works

**Comment by geoffblay** [comment]
if it doesn't work on first run:
`npm i supabase@">=1.8.1" --save-dev ; npx supabase login`
To generate access token (save this somewhere): [https://supabase.com/dashboard/account/tokens]
After successful login, run script again and it should work.

**Review by MrEminent42 — CHANGES_REQUESTED** [review]
Awesome stuff. I'm really excited to pull these in automatically. Just one thing to clean up + merge with main, and you should be good to go!

**Review by MrEminent42 — APPROVED** [review]
Let's go

**Review by MrEminent42 — APPROVED** [review]
Merge hell!

**Pull request merged**
