### PR TITLE
Geoff/view task

### LINKED ISSUE #48: Use Case: View Tasks
System should provide a list of all tasks related to the selected property on the Tasks screen.

### PR DESCRIPTION
**Pull request by geoffblay**
General description of changes:
* Adds functionality for viewing tasks for a property consistent with the database.
* Property card on the home page now updates to show correct number of corresponding tasks.
* Colors added!

Breaking changes: 
* None I think

Did you run `npm run before-pr`?
- [X] yes
- [ ] no

Does this PR fix/implement an Issue?
- [X] yes, fixes #48 
- [ ] no

### CODE REVIEW

**Review by zachstoney30 — APPROVED** [review]

**Review by MrEminent42 — CHANGES_REQUESTED** [review]
Amazing. Well done with the "days left" vs "overdue." Really exciting to see this come together.

Couple things:
* Naming something `WhateverComponent` is a bit redundant since it's a component. 
* Putting a function at the bottom of the file (esp after Styled Components) seems a bit weird to me. In Javascript you can actually put it inside a function. Maybe put it at line 51?
* Please pull from `main` and solve merge conflicts before making PR

**Review by bri-personal — CHANGES_REQUESTED** [review]
UI looks great but there's an issue with the "days left"/"overdue" string. It looks like the daysBetween function you're using returns the absolute value of days between two dates, so if a task is set for Today it says overdue, and if it's set # days _before_, it incorrectly says "# days left". (IMO something due Today shouldn't be overdue, but we can discuss that.) Leo suggests **moment.js** as an alternative for calculating date differences.

Also please pull from main to bring in the UI changes for adding a task and to prevent any conflicts.

**Comment by geoffblay** [comment]
fixed due date bug, pulled from main

**Comment by geoffblay** [comment]
colors added woohoo

**Comment by geoffblay** [comment]
now uses supabase types instead of Types.ts

**Review by MrEminent42 — APPROVED** [review]
Looks amazing :)

**Review by bri-personal — APPROVED** [review]
good now

**Pull request merged**
