### PR TITLE
Added functionality for "add new property" use case

### LINKED ISSUE #31: Use Case: Add Property
The user should be able to add a property, specifying all of the property's characteristics.

The property should be added to the `Properties` table on Supabase. Rooms should be added to the `Rooms` table and be related to Properties via the `RoomsInProperties` table.

### PR DESCRIPTION
**Pull request by bri-personal**
General description of changes:
* Adds functionality for "Add new property" use case. On clicking page, can input all info, set picture, and add rooms as a comma separated value string. Drag and Drop photo DOES NOT WORK YET but if you click on the place where it says drag and drop it opens a window to select an image file.
* Changes url path to the add property page, so it isn't generic "/1" anymore

Breaking changes: 

* dependencies are updated so run npm install after pulling

Did you run `npm run before-pr`?

- [X] yes
- [ ] no

Does this PR fix/implement an Issue?

- [X] yes, fixes #31
- [ ] no

Other notes:

### CODE REVIEW

**Review by geoffblay — APPROVED** [review]
this looks really good. My only suggestion would be to find a different house placeholder image that is at least 300px in width so that it doesn't cause weird resizing when you upload a real house image. Other than that this is great, approved.

**Review by zachstoney30 — APPROVED** [review]
Looks really great Bri

**Review by MrEminent42 — CHANGES_REQUESTED** [review]
Really awesome stuff. I like how you handled the changing of states for the form. Some functionality we should fix, but most of this review is suggestions and nitpicks . Generally, let's move away from `alert()` unless it's an error that should be given to the user. Well done Brian!

**Review by MrEminent42 — APPROVED** [review]
Looks a ton better. Thanks!

**Pull request merged**
