### PR TITLE
Refactor: Clean up

### PR DESCRIPTION
**Pull request by MrEminent42**
General description of changes:
* Refactors tasks page to create TaskSection component
* Add user-facing error-handling function that logs to console and attempts to alert relevant information to the user

Breaking changes: 

* HEADS UP: error handling should now be done with the `displayError` method, in `App.tsx`. See the file changes for an example. This will make things simpler and easier to update, down the road.

Did you run `npm run before-pr`?

- [x] yes
- [ ] no

Does this PR fix/implement an Issue?

- [ ] yes, fixes #XX
- [x] no

Other notes:

### CODE REVIEW

**Review by bri-personal — CHANGES_REQUESTED** [review]
this seems like a good place to change the name of Tasks to not Page2. Otherwise awesome!

**Review by bri-personal — APPROVED** [review]

**Review by bri-personal — CHANGES_REQUESTED** [review]
When I open the home screen or go back to the home screen by clicking the logo or the back button in a property page, nothing loads until I go into the add/edit screen and then exit from there. I think something you changed made my refresh thing work weird.

Also, when I mark a task as completed, it disappears from the To Do section, but it doesn't show up in the Completed section like it did before.

**Comment by MrEminent42** [comment]
Fixed, sorry about that

**Review by bri-personal — APPROVED** [review]
yay

**Review by bri-personal — APPROVED** [review]
yay

**Review by geoffblay — APPROVED** [review]

**Pull request merged**
